"""Animation / timeline slot names of the game's state graphs (DSGs).

A model stores slot *ids* (positions in its state graph's slot lists); the graph name is not in the BLP, but the number of timeline slots
identifies it for nearly all models. Generated from the SDK Development Assets (Civ6/pantry/DSGs and DLC); slot names are plain enum names.
"""

DSGS = {
    'potential_any_graph_with_jump': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'BREATHING_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'BREATHING_COMBAT_A', 'IDLE_COMBAT_A', 'IDLE_COMBAT_B', 'IDLE_COMBAT_C', 'IDLE_COMBAT_D', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_STOP_B', 'RUN_STOP_D', 'RUN_STOP_C', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START', 'ACTION_1', 'DEATH_21', 'DEATH_22', 'DEATH_23', 'DEATH_24', 'DEATH_25', 'DEATH_26', 'DEATH_27', 'DEATH_28', 'JUMP_START', 'JUMP_IDLE', 'JUMP_STOP', 'DEFEND_2', 'DEFEND_3'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'IDLE_COMBAT_B', 'IDLE_COMBAT_C', 'IDLE_COMBAT_D', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START', 'ACTION_1', 'DEATH_21', 'DEATH_22', 'DEATH_23', 'DEATH_24', 'DEATH_25', 'DEATH_26', 'DEATH_27', 'DEATH_28', 'JUMP_START', 'JUMP_IDLE', 'JUMP_STOP', 'DEFEND_2', 'DEFEND_3']),
    'Landmark_Activated': (
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A', 'ACTIVATED_A'],
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A', 'ACTIVATED_A']),
    'Landmark_WaterMill': (
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_FLOW_RIGHT_A', 'UNWORKED_A', 'PILLAGED_A', 'WORKED_FLOW_LEFT_A', 'WORKED_A'],
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_FLOW_RIGHT_A', 'UNWORKED_A', 'PILLAGED_A', 'WORKED_FLOW_LEFT_A', 'WORKED_A']),
    'Standard_Biped': (
        ['RUN_A', 'IDLE_A', 'DEATH_A'],
        ['RUN_A', 'IDLE_A', 'ATTACK_A', 'DEATH_A']),
    'Standard_Broadside': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'BREATHING_A', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_P', 'DEFEND_P', 'HERO_LEFT', 'RUN_COMBAT', 'REACT_RANGED', 'VICTORY', 'ATTACK_S', 'HERO_RIGHT', 'DEFEND_S', 'RUN_COMBAT_STOP', 'RUN_STOP', 'ATTACK_1', 'ATTACK_2', 'ATTACK_3', 'ATTACK_4', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_P', 'DEFEND_P', 'HERO_LEFT', 'RUN_COMBAT', 'REACT_RANGED', 'VICTORY', 'ATTACK_S', 'HERO_RIGHT', 'DEFEND_S', 'RUN_COMBAT_STOP', 'RUN_STOP', 'ATTACK_1', 'ATTACK_2', 'ATTACK_3', 'ATTACK_4', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20']),
    'Standard_CannonBlast': (
        [],
        ['FIRE']),
    'Standard_Clutter': (
        ['IDLE_A'],
        ['IDLE_A']),
    'Standard_Clutter_Activated': (
        ['IDLE_A', 'ACTIVATED_A'],
        ['IDLE_A', 'ACTIVATED_A']),
    'Standard_Dog': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'BREATHING_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_STOP_B', 'RUN_STOP_D', 'RUN_STOP_C', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START', 'IDLE_COMBAT_A', 'IDLE_COMBAT_B', 'IDLE_COMBAT_C', 'IDLE_COMBAT_D'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START']),
    'Standard_GunMuzzleFlash': (
        [],
        ['FIRE']),
    'Standard_Landmark': (
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A', 'IDLE_A'],
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A', 'IDLE_A']),
    'Standard_LandmarkNoRandomOffset': (
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A'],
        ['CONSTRUCTION_A', 'UNBUILT_A', 'WORKED_A', 'UNWORKED_A', 'PILLAGED_A']),
    'Standard_Leader': (
        ['NEUTRAL_IDLE_A', 'HAPPY_IDLE_A', 'UNHAPPY_IDLE_A', 'NEUTRAL_POSITIVE_A', 'NEUTRAL_POSITIVE_B', 'NEUTRAL_NEGATIVE_A', 'NEUTRAL_NEGATIVE_B', 'HAPPY_POSITIVE_A', 'HAPPY_POSITIVE_B', 'HAPPY_NEGATIVE_A', 'HAPPY_NEGATIVE_B', 'UNHAPPY_POSITIVE_A', 'UNHAPPY_POSITIVE_B', 'UNHAPPY_NEGATIVE_A', 'UNHAPPY_NEGATIVE_B', 'DECLARE_WAR_A', '01_FIRST_MEET', '02_DECLARE_WAR_FROM_HUMAN', '03_DECLARE_WAR_FROM_AI', '04_KUDOS', '05_WARNING', '06_DEFEAT', 'NEUTRAL_TO_HAPPY', 'NEUTRAL_TO_UNHAPPY', 'NEUTRAL_TO_ENRAGED', 'HAPPY_TO_NEUTRAL', 'HAPPY_TO_ENRAGED', 'UNHAPPY_TO_NEUTRAL', 'UNHAPPY_TO_ENRAGED'],
        ['NEUTRAL_IDLE_A', 'HAPPY_IDLE_A', 'UNHAPPY_IDLE_A', 'NEUTRAL_POSITIVE_A', 'NEUTRAL_POSITIVE_B', 'NEUTRAL_NEGATIVE_A', 'NEUTRAL_NEGATIVE_B', 'HAPPY_POSITIVE_A', 'HAPPY_POSITIVE_B', 'HAPPY_NEGATIVE_A', 'HAPPY_NEGATIVE_B', 'UNHAPPY_POSITIVE_A', 'UNHAPPY_POSITIVE_B', 'UNHAPPY_NEGATIVE_A', 'UNHAPPY_NEGATIVE_B', 'DECLARE_WAR_A', '01_FIRST_MEET', '02_DECLARE_WAR_FROM_HUMAN', '03_DECLARE_WAR_FROM_AI', '04_KUDOS', '05_WARNING', '06_DEFEAT', 'NEUTRAL_TO_HAPPY', 'NEUTRAL_TO_UNHAPPY', 'NEUTRAL_TO_ENRAGED', 'HAPPY_TO_NEUTRAL', 'HAPPY_TO_ENRAGED', 'UNHAPPY_TO_NEUTRAL', 'UNHAPPY_TO_ENRAGED']),
    'Standard_LeaderBackground': (
        ['ENTER_ROOM', 'IDLE'],
        ['ENTER_ROOM', 'IDLE']),
    'Standard_Leader_No_Unhappy_Blend': (
        ['NEUTRAL_IDLE_A', 'HAPPY_IDLE_A', 'UNHAPPY_IDLE_A', 'NEUTRAL_POSITIVE_A', 'NEUTRAL_POSITIVE_B', 'NEUTRAL_NEGATIVE_A', 'NEUTRAL_NEGATIVE_B', 'HAPPY_POSITIVE_A', 'HAPPY_POSITIVE_B', 'HAPPY_NEGATIVE_A', 'HAPPY_NEGATIVE_B', 'UNHAPPY_POSITIVE_A', 'UNHAPPY_POSITIVE_B', 'UNHAPPY_NEGATIVE_A', 'UNHAPPY_NEGATIVE_B', 'DECLARE_WAR_A', '01_FIRST_MEET', '02_DECLARE_WAR_FROM_HUMAN', '03_DECLARE_WAR_FROM_AI', '04_KUDOS', '05_WARNING', '06_DEFEAT', 'NEUTRAL_TO_HAPPY', 'NEUTRAL_TO_UNHAPPY', 'NEUTRAL_TO_ENRAGED', 'HAPPY_TO_NEUTRAL', 'HAPPY_TO_ENRAGED', 'UNHAPPY_TO_NEUTRAL', 'UNHAPPY_TO_ENRAGED'],
        ['NEUTRAL_IDLE_A', 'HAPPY_IDLE_A', 'UNHAPPY_IDLE_A', 'NEUTRAL_POSITIVE_A', 'NEUTRAL_POSITIVE_B', 'NEUTRAL_NEGATIVE_A', 'NEUTRAL_NEGATIVE_B', 'HAPPY_POSITIVE_A', 'HAPPY_POSITIVE_B', 'HAPPY_NEGATIVE_A', 'HAPPY_NEGATIVE_B', 'UNHAPPY_POSITIVE_A', 'UNHAPPY_POSITIVE_B', 'UNHAPPY_NEGATIVE_A', 'UNHAPPY_NEGATIVE_B', 'DECLARE_WAR_A', '01_FIRST_MEET', '02_DECLARE_WAR_FROM_HUMAN', '03_DECLARE_WAR_FROM_AI', '04_KUDOS', '05_WARNING', '06_DEFEAT', 'NEUTRAL_TO_HAPPY', 'NEUTRAL_TO_UNHAPPY', 'NEUTRAL_TO_ENRAGED', 'HAPPY_TO_NEUTRAL', 'HAPPY_TO_ENRAGED', 'UNHAPPY_TO_NEUTRAL', 'UNHAPPY_TO_ENRAGED']),
    'Standard_Naval': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_P', 'DEFEND_P', 'HERO_LEFT', 'RUN_COMBAT', 'REACT_RANGED', 'VICTORY', 'ATTACK_S', 'HERO_RIGHT', 'DEFEND_S', 'RUN_COMBAT_STOP', 'RUN_STOP', 'ATTACK_1', 'ATTACK_2', 'ATTACK_3', 'ATTACK_4', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_P', 'DEFEND_P', 'HERO_LEFT', 'RUN_COMBAT', 'REACT_RANGED', 'VICTORY', 'ATTACK_S', 'HERO_RIGHT', 'DEFEND_S', 'RUN_COMBAT_STOP', 'RUN_STOP', 'ATTACK_1', 'ATTACK_2', 'ATTACK_3', 'ATTACK_4', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20']),
    'Standard_NonCombat': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'BREATHING_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ACTION_A', 'DEATH_1', 'DEATH_A', 'DEATH_2', 'DEATH_3', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ACTION_1', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_STOP_B', 'RUN_STOP_D', 'RUN_STOP_C', 'RUN_START', 'ACTION_2', 'ACTION_3', 'ACTION_4', 'IDLE_COMBAT_A'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ACTION_A', 'DEATH_1', 'DEATH_A', 'DEATH_2', 'DEATH_3', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ACTION_1', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_START', 'ACTION_2', 'ACTION_3', 'ACTION_4', 'IDLE_COMBAT_A']),
    'Standard_NonCombatNaval': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'BREATHING_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ACTION_A', 'DEATH_1', 'DEATH_A', 'DEATH_2', 'DEATH_3', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ACTION_1', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_STOP_B', 'RUN_STOP_D', 'RUN_STOP_C', 'RUN_START', 'ACTION_2', 'ACTION_3', 'ACTION_4', 'REACT_RANGED', 'ATTACK_1'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ACTION_A', 'DEATH_1', 'DEATH_A', 'DEATH_2', 'DEATH_3', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ACTION_1', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_START', 'ACTION_2', 'ACTION_3', 'ACTION_4', 'REACT_RANGED', 'ATTACK_1']),
    'Standard_SwordTrail': (
        [],
        ['SWING']),
    'Standard_TerrainElementAsset': (
        ['IDLE_A'],
        ['IDLE_A']),
    'Standard_VFX': (
        ['IDLE_A'],
        ['IDLE_A']),
    'Standard_VFX_RandomOffset': (
        ['IDLE_A'],
        ['IDLE_A']),
    'Standard_WonderMovie': (
        ['REVEAL_A', 'CONSTRUCTION_A', 'WORKED_A', 'RUINED_A'],
        ['REVEAL_A', 'CONSTRUCTION_A', 'WORKED_A', 'RUINED_A']),
    'potential_any_graph': (
        ['RUN_A', 'FORWARD_A', 'BACKWARD_A', 'BREATHING_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'BREATHING_COMBAT_A', 'IDLE_COMBAT_A', 'IDLE_COMBAT_B', 'IDLE_COMBAT_C', 'IDLE_COMBAT_D', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_STOP_B', 'RUN_STOP_D', 'RUN_STOP_C', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START', 'ACTION_1', 'DEATH_27', 'DEATH_26', 'DEATH_25', 'DEATH_24', 'DEATH_23', 'DEATH_22', 'DEATH_21', 'DEATH_28'],
        ['RUN_A', 'PERSISTENT', 'FORWARD_A', 'BACKWARD_A', 'IDLE_A', 'IDLE_B', 'IDLE_D', 'IDLE_C', 'ATTACK_A', 'REACT_A', 'DEATH_1', 'DEATH_A', 'DODGE_A', 'HERO_A', 'SPAWN', 'DEATH_2', 'DEATH_3', 'IDLE_COMBAT_A', 'IDLE_COMBAT_B', 'IDLE_COMBAT_C', 'IDLE_COMBAT_D', 'DEFEND_A', 'DEATH_4', 'DEATH_5', 'DEATH_6', 'TURN_R', 'TURN_L', 'DEATH_7', 'DEATH_8', 'DEATH_10', 'DEATH_11', 'DEATH_12', 'DEATH_13', 'DEATH_14', 'DEATH_9', 'ATTACK_1', 'DEFEND_1', 'HERO_1', 'RUN_COMBAT', 'REACT_RANGED_A', 'REACT_RANGED_B', 'REACT_RANGED_D', 'REACT_RANGED_C', 'VICTORY', 'DEATH_15', 'DEATH_16', 'DEATH_17', 'DEATH_18', 'DEATH_19', 'DEATH_20', 'RUN_STOP', 'RUN_COMBAT_STOP', 'RUN_START', 'ATTACK_2', 'ATTACK_3', 'RUN_COMBAT_START', 'ACTION_1', 'DEATH_27', 'DEATH_26', 'DEATH_25', 'DEATH_24', 'DEATH_23', 'DEATH_22', 'DEATH_21', 'DEATH_28']),
}
